
name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: ["main"]
  pull_request:
    branches: [ "main" ]

concurrency: production

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}
          fetch-depth: '0'

      - name: Dry Run - Increment Patch for Each Commit
        id: taggerDryRun
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DRY_RUN: true
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Checkout Repository'
        uses: actions/checkout@main

      - name: 'Build Docker Image and Push to GHCR'
        run: |
          docker build . --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{steps.taggerDryRun.outputs.new_tag}}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{steps.taggerDryRun.outputs.new_tag}}

    # IN CASE OF FAILURE, THE STEP BELOW WILL NOT RUN.

      - name: Final - Increment Patch for Each Commit
        id: taggerFinal
        uses: anothrnick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: main


